---
booktitle: 'Proceedings of UniReps: the Second Edition of the Workshop on Unifying
  Representations in Neural Models'
shortname: UniReps
year: '2024'
volume: '285'
start: &1 2024-12-14
end: 2024-12-14
published: 2024-06-15
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: unireps24
month: 0
cycles: false
bibtex_editor: Fumero, Marco and Domine, Clementine and L{\"a}hner, Zorah and Crisostomi,
  Donato and Moschella, Luca and Stachenfeld, Kimberly
editor:
- given: Marco
  family: Fumero
- given: Clementine
  family: Domine
- given: Zorah
  family: Lähner
- given: Donato
  family: Crisostomi
- given: Luca
  family: Moschella
- given: Kimberly
  family: Stachenfeld
title: Proceedings of Machine Learning Research
description: |
  Proceedings of UniReps: the Second Edition of the Workshop on Unifying Representations in Neural Models
    Held in Vancouver Convention Center,Vancouver, Canada on 14 December 2024

  Published as Volume 285 by the Proceedings of Machine Learning Research on 15 June 2024.

  Volume Edited by:
    Marco Fumero
    Clementine Domine
    Zorah Lähner
    Donato Crisostomi
    Luca Moschella
    Kimberly Stachenfeld

  Series Editors:
    Neil D. Lawrence
date_str: 14 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v285"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v285
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v285
email: ''
conference:
  name: 'Proceedings of UniReps: the Second Edition of the Workshop on Unifying Representations
    in Neural Models'
  url: https://unireps.org
  location: Vancouver Convention Center,Vancouver, Canada
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: unireps24.bib
# Site settings
# Original source:  unireps24.bib
